# config/_default/languages.es.toml

languageCode = "es"
languageName = "Español"
weight = 1

title = "mariomenjr.com"

[params]
  isoCode = "es"
  displayName = "ES"

[author]
  name = "Mario Menjívar"
  image = "img/author.jpg"
  headline = "Curiosity-driven human. Computer scientist. Immigrant."
  bio = "Curiosity-driven human. Computer scientist. Immigrant."
  links = [
    { linkedin = "https://linkedin.com/in/mariomenjr" },
    { email = "mailto:mariomenjr@gmail.com" },
    { github = "https://github.com/mariomenjr" },
    { youtube = "https://youtube.com/mariomenjr" },
    { twitter = "https://twitter.com/mariomenjr" },
  ]