# config/_default/params.toml

colorScheme = "slate"
enableCodeCopy = true

[homepage]
  layout = "profile"
  showRecent = true

[article]
  showEdit = true
  editURL = "https://github.com/mariomenjr/mariomenjr/edit/main/content"
  showTableOfContents = true
  showBreadcrumbs = true
  # showWordCount = true
  # showTableOfContents = false
  sharingLinks = ["facebook", "twitter", "mastodon", "pinterest", "reddit", "linkedin", "email"]
  
[footer]
  showAppearanceSwitcher = true