# config/_default/params.toml

colorScheme = "slate"

[homepage]
  layout = "profile"
  showRecent = true

[article]
  showEdit = true
  editURL = "https://github.com/mariomenjr/mariomenjr/edit/main/content"
  showTableOfContents = true
  showBreadcrumbs = true