# config/_default/params.toml

colorScheme = "slate"
enableCodeCopy = true
robots = "noarchive"

[homepage]
  layout = "profile"
  showRecent = true

[article]
  showEdit = true
  editURL = "https://github.com/mariomenjr/mariomenjr/edit/main/content"
  showTableOfContents = true
  showBreadcrumbs = true
  # showWordCount = true
  # showTableOfContents = false
  sharingLinks = ["facebook", "twitter", "mastodon", "reddit", "linkedin"]
  
[footer]
  showAppearanceSwitcher = true

[verification]
  google="NspysIBon3Yhy_TQbJtYWM7ffCfRAC2ncngp4s8-hLI"